src/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do 
      get :choose_new_type
      get :new_books
      get :new_cloth
      get :new_snacks
      get :category_products
      post :create_books
      post :create_snacks
      post :create_cloth
    end

    member do
      get :buy
      get :put_in_cart
    end
  end

  resources :cart_products do
    collection do
      get :show_cart
      get :update_quantity
    end
    member do
      get :destory
    end
  end

  resources :orders do
    collection do
      get :show_order
      post :new_cart_orders
      post :create_cart_orders
      get :pay_for_orders
      get :request_manager
    end

    member do
      get :purchase
      get :check_out
      get :pay
      delete :destroy
      get :approval
      get :update_reject_status
      patch :reject
      get :refund
      get :confirm
      get :ship
    end
  end

  devise_for :users

  root to: 'homepage#home'
  match '/help',    to: 'homepage#help',    via: 'get'
  match '/about',   to: 'homepage#about',   via: 'get'
  match '/contact', to: 'homepage#contact', via: 'get'
end

src/app/models/product.rb
class Product < ActiveRecord::Base
	actable
	has_many :images
	validates :quantity,
						:presence => true,
						:numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }


=begin
	According to the keyword return the related products, page is used to pagination
=end
	def self.search(search, page)
		if search
			order('title').where('title LIKE ?', "%#{search}%").paginate(page: page, per_page: 8)
		else
			order('title').all.paginate(page: page, per_page: 8)
		end
	end

=begin
	According to the type and category, return the realated products, page is used to pagination
=end
	def self.category_products(type, category, page)
		if type && category
			@products = order("created_at DESC").where(actable_type: type, category: category).paginate(page: page, per_page: 8)
		elsif type
			@products = order("created_at DESC").where(actable_type: type).paginate(page: page, per_page: 8)
		end
		return @products
	end

end

src/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show, :category_products]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /products
  # GET /products.json
  # return the products list
  def index
    @products = Product.search(params[:search], params[:page])
  end

  # return the products of one category of one type
  def category_products
    @products = Product.category_products(params[:type], params[:category], params[:page])
    render :index
  end

  # GET /products/1
  # GET /products/1.json
  # show the detail of the product
  def show
    @image_path = @product.images.first.path_url
  end

  def choose_new_type
  end

  def new_books
    @product = Book.new
  end
  
  def create_books
    @book = Book.new(product_params)
    @image = Image.new
    if(!params[:book][:image].blank?)
      @image.path = params[:book][:image]
    else
      @image.path = "default.png"
    end
    @book.images << @image
    @book.seller_id = current_user.id
    respond_to do |format|
      if @book.save
        format.html { render :create_products_successful, notice: 'Product was successfully created.' }
        format.json { render :create_products_successful, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_cloth
    @product = Cloth.new
  end

  def create_cloth
    @cloth = Cloth.new(product_params)
    @image = Image.new
    if(!params[:cloth][:image].blank?)
      @image.path = params[:cloth][:image]
    else
      @image.path = "default.png"
    end
    @cloth.images << @image
    respond_to do |format|
      if @cloth.save
        format.html { render :create_products_successful, notice: 'Product was successfully created.' }
        format.json { render :create_products_successful, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_snacks
    @product = Snack.new
  end

  def create_snacks
    @snack = Snack.new(product_params)
    @image = Image.new
    if(!params[:snack][:image].blank?)
      @image.path = params[:snack][:image]
    else
      @image.path = "default.png"
    end
    @snack.images << @image
    respond_to do |format|
      if @snack.save
        format.html { render :create_products_successful, notice: 'Product was successfully created.' }
        format.json { render :create_products_successful, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    if params.keys.include? "book"
        attributes = params.require(:book).permit(:name, :price, :description)
        @product = Book.new(attributes)
    elsif params.keys.include? "cloth"
        attributes = params.require(:cloth).permit(:name, :quantity, :price, :description)
        @product = Book.new(attributes)
    elsif params.keys.include? "snack"
        attributes = params.require(:snack).permit(:name, :quantity, :price, :description)
        @product = Book.new(attributes)
    end
    # render :create_products_successful
    respond_to do |format|
      if @product.save
        format.html { render :create_products_successful, notice: 'Product was successfully created.' }
        format.json { render :create_products_successful, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      if params.keys.include? "book"
        params.require(:book).permit(:name, :quantity, :price, :description, :category, :title, :author, :publisher)
      elsif params.keys.include? "cloth"
        params.require(:cloth).permit(:name, :quantity, :price, :description)
      elsif params.keys.include? "snack"
        params.require(:snack).permit(:name, :quantity, :price, :description)
      end
      # params.require(:product).permit(:name, :quantity, :price, :description)
    end
end

src/app/helpers/products_helper.rb
module ProductsHelper
end

src/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seller_id %><br>
    <%= f.number_field :seller_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :actable_id %><br>
    <%= f.number_field :actable_id %>
  </div>
  <div class="field">
    <%= f.label :actable_type %><br>
    <%= f.text_field :actable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/products/category.html.erb
<p id="notice"><%= notice %></p>
<h1>Products List</h1>

<table>
  <thead>
    <tr>
      <th>Seller</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Description</th>
      <th>Actable</th>
      <th>Actable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.seller_id %></td>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'detail', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%=will_paginate(@products, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | ") %>
<%= link_to 'New Product', new_product_path %>

src/app/views/products/choose_new_type.html.erb
<h2>Tell us what you're selling</h2>
<%= link_to 'Books', new_books_products_path %> </br>
<%= link_to 'Cloth', new_cloth_products_path %> </br>
<%= link_to 'Snacks', new_snacks_products_path %> </br>

src/app/views/products/create_products_successful.html.erb
<h1>Your Products Are Selling Now!</h1>
<%= link_to 'Provide another sale', choose_new_type_products_path %> </br>
<%= link_to 'Go back to Home', root_path %> </br>

src/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

src/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Products List</h1>

<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
  <tr style = "text-align:center;">
    <th style = "text-align:center;"></th>
    <th style = "text-align:center;">Title</th>
    <th style = "text-align:center;">Name</th>
    <th style = "text-align:center;">Quantity</th>
    <th style = "text-align:center;">Price</th>
    <th style = "text-align:center;">Type</th>
    <th style = "text-align:center;">Go to Detail</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= link_to image_tag(product.images.first.path_url, size:"80", id: "prouctImage"),product%></td>
        <td><%= link_to product.title ,product%></td>
        <td><%= link_to product.name ,product%></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.actable_type %></td>
        <td><%= link_to 'detail', product %></td>
      </tr>
  <% end %>
  </tbody>
</table>



<br>
<%=will_paginate(@products, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | ") %>

src/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

src/app/views/products/new_books.html.erb
<h2>Please fill out the details about the books you are selling</h2>

<%= form_for @product, url: create_books_products_path(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <ul>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :Quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :Bookname %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :category %><br>
  <%= f.select(:category, ['Textbook', 'ChildrenBook', 'Novel'], :class => 'my_style_class')%>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= link_to 'Back', :back %>
   </ul>
<% end %>

src/app/views/products/new_cloth.html.erb
<h1>Please fill out the details about the cloth you are selling</h1>

<%= form_for @product, url: create_cloth_products_path(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :garment_care %><br>
    <%= f.text_field :garment_care %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :category %><br>
  <%= f.select(:category, ['ChipsCrips', 'Cookies', 'Jerky', 'NutsSeeds'], :class => 'my_style_class')%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

src/app/views/products/new_snacks.html.erb
<h1>Please fill out the details about the snacks you are selling</h1>

<%= form_for @product, url: create_snacks_products_path(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :Snackname %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :manufacture_date %><br>
    <%= f.datetime_select :manufacture_date %>
  </div>
  <div class="field">
    <%= f.label :best_before %><br>
    <%= f.datetime_select :best_before %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :production_place %><br>
    <%= f.text_field :production_place %>
  </div>
  <div class="field">
    <%= f.label :ingredient %><br>
    <%= f.text_field :ingredient %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
  <%= f.label :category %><br>
  <%= f.select(:category, ['Top', 'Bottom', 'Outwear'], :class => 'my_style_class')%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

src/app/views/products/show.html.erb
<p id="notice" xmlns:class="http://www.w3.org/1999/xhtml"><%= notice %></p>

<div><%= image_tag @image_path, size:"500" %></div>
<div>
<dl class="dl-horizontal">
  <% @product.specific.attributes.each_pair do |name, value| %>

    <% if name != "created_at" && name != "updated_at" && name != "id" && name != "seller_id" && name != "actable_id" && name != "actable_type" && name != "lock_version" %>
    <dt><%= name %></dt>
    <dd><%= value %></dd>
    <% end %>

  <% end %>
  

  <dt> Purchase Num:</dt>
  <dd><%= number_field(:purchase, :quantity, in: 1..@product.quantity, step: 1, value: 1, class: "span3") %></dd>
</dl>
</div>
<div class="btn-toolbar" role="toolbar" >
  <div class="btn-group" role="group" aria-label="Buy now">
    <button type="button" class="btn btn-success" id = "buynow">Buy now</button>
</div>
<div class="btn-group" role="group" aria-label="Put in cart">
    <button type="button" class="btn btn-primary" id = "putcart">Put in cart</button>
</div>
<div>
  <%= link_to 'Back', :back, class: "btn btn-default"%>
</div>
  </div>