src/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do 
      get :choose_new_type
      get :new_books
      get :new_cloth
      get :new_snacks
      get :category_products
      post :create_books
      post :create_snacks
      post :create_cloth
    end

    member do
      get :buy
      get :put_in_cart
    end
  end

  resources :cart_products do
    collection do
      get :show_cart
      get :update_quantity
    end
    member do
      get :destory
    end
  end

  resources :orders do
    collection do
      get :show_order
      post :new_cart_orders
      post :create_cart_orders
      get :pay_for_orders
      get :request_manager
    end

    member do
      get :purchase
      get :check_out
      get :pay
      delete :destroy
      get :approval
      get :update_reject_status
      patch :reject
      get :refund
      get :confirm
      get :ship
    end
  end

  devise_for :users

  root to: 'homepage#home'
  match '/help',    to: 'homepage#help',    via: 'get'
  match '/about',   to: 'homepage#about',   via: 'get'
  match '/contact', to: 'homepage#contact', via: 'get'
end

src/app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_products
	attr_reader :product_id, :amount


	# return the order list according to the correct type
	def self.show_order(type, page, current_user_id)
		if type == 'purchase'
			order("created_at DESC").where(buyer_id: current_user_id).paginate(page: page, per_page: 8)
		elsif type == 'sell'
			order("created_at DESC").where(seller_id: current_user_id).paginate(page: page, per_page: 8)
		elsif type == 'revoke'
			order("created_at DESC").where(status: 'Pending').paginate(page: page, per_page: 8)
		end
	end

=begin
Overwrite constructor of order calling private function set_attributes, enable generating OrderProduct for order.
@param attributes[optional]
=end

	def initialize attributes = nil
		if attributes
			@amount = attributes["amount"]
			@current_user_id = attributes["current_user_id"]
			@product_id = attributes["product_id"]
			excludes = [ "current_user_id" ,"product_id", "amount"]
			attributes.except!( *excludes )
		end
		super attributes
		set_attributes unless attributes == nil
	end

=begin
Private function set_attributes, called by initialise. create OrderProduct for generated order and set other attributes
=end
	def set_attributes
		product = Product.find @product_id
		total_price = @amount.to_d * product.price.to_d
   		attributes = {buyer_id: @current_user_id, seller_id: product.seller_id, status: "unpaid", total_price: total_price}
   		self.attributes = attributes
   		attrs = {product_id: @product_id, quantity: @amount}
   		order_product = OrderProduct.new attrs
   		self.order_products << order_product
	end

=begin
Used by “buy it now” feature, to decrease quantity of product after corresponding order is created.
=end
	def decrease_correspoding_product
		product = Product.find @product_id
		product.update_attributes!(quantity: product.quantity-@amount.to_i)
	end

=begin
Static method create_cart_orders, used for checkout from cart. This method using transaction to ensure 
orders of every selected product successfully created. Otherwise, rollback all operations and return error information.
@param cart_products, current_user_id, cart_order_params
=end
	def self.create_cart_orders cart_products, current_user_id, cart_order_params
		seller_orders = {}
		orders_generated = []
		Order.transaction do
			cart_products.each do |cart_product_id|
		      cart_product = CartProduct.find cart_product_id
		      product = Product.find cart_product.product_id
	      	  product.update_attributes(quantity: product[:quantity]-cart_product[:quantity])
		      if seller_orders.has_key? product.seller_id
		      	attrs = {product_id: cart_product[:product_id], quantity: cart_product[:quantity]}
	   			order_product = OrderProduct.new attrs
		      	seller_orders[product.seller_id].order_products << order_product
		      else
		      	attrs = {"product_id" => cart_product.product_id, "current_user_id" => current_user_id, "amount" => cart_product[:quantity]}
		      	attrs.merge! cart_order_params
		      	order = Order.new attrs
		      	seller_orders[product.seller_id] = order
		      end
		      CartProduct.destroy(cart_product_id)
	   		end
	   		seller_orders.each do |seller, order|
   				total_price = 0
	   			order.order_products.each do |order_product|
	   				product = Product.find order_product.product_id
	   				total_price += product.price*order_product.quantity
	   			end
	   			order.total_price = total_price
	   			if order.save_order
	   				@message = "success"
	   				orders_generated << order.id
	   			else
	   				@message = "seller_id: " + seller + "'s order: " + order.to_s + "fail to generated!"
	   			end
	   		end
   		end
   		return @message=="success"? orders_generated : @message
	end

=begin
save_order
Using transaction to ensure failure order generation will not influence quantity of product
and using optimistic locking to ensure concurrence when multiple user attempt to change quantity of one product at the same time.
=end
	def save_order
	    product = Product.find @product_id
	    product_quantity = product[:quantity]
	    signal = false
	    quantity_runout = false
	    Order.transaction do
	      self.save!
	      logger.info "Order : "+ self.id.to_s+" is successfully created"
	      until quantity_runout do
	        begin
	          decrease_correspoding_product
	        rescue ActiveRecord::StaleObjectError
	          quantity_runout = true unless product_quantity >= @amount
	          next
	        else
	          signal = true
	          break
	        end
	      end 
	    end
	    logger.info "Product : " + @product_id.to_s + "'s quantity run out!" unless !quantity_runout
	    return signal
	end


	private :set_attributes
end

src/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :check_out, :pay, :approval, :update_reject_status, :refund, :reject, :confirm, :ship]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  # create a new order
  def new
    @order = Order.new
    @product_params = {amount: params["amount"], product_id: params["productId"]}
    render :new
  end

  # POST /orders
  # POST /orders.json
  # save one order in the database
  def create
    attributes = {"current_user_id" => current_user.id}
    request_params = order_params
    attributes.merge! request_params
    @order = Order.new(attributes)
    signal = @order.save_order
    respond_to do |format|
      if signal
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /orders/1/edit
  def edit
  end

  # render the view to let the user enter the information about the order
  def new_cart_orders
    @order = Order.new
    session[:selected_cart_products] = params[:cart_product_ids]
  end

  # create orders for selected items in the cart
  def create_cart_orders
    cart_order_params = params.permit(:name, :postcode, :address, :phone, :product_id, :amount, :current_user_id)
    message = Order.create_cart_orders session[:selected_cart_products], current_user.id, cart_order_params
    if message.instance_of? Array
      session[:orders_generated] = message
      respond_to do |format|
        format.html { render create_cart_orders_orders_path, notice: 'Orders was successfully created.' }
      end
    else
      respond_to do |format|
        format.html { render show_cart_cart_products_path, notice: message }
      end
    end
  end

  def check_out
  end

  # pay for one order
  def pay_for_orders
    orders_selected = session[:orders_generated]
    orders_selected.each do |order|
      order_generated = Order.find order
      order_generated.update_attribute(:status, "Paid")
    end
  end

  def pay
    @order.update_attribute(:status, "Paid")
    render :pay_for_orders
  end

  # show the information of one order
  def show_order
    @orders = Order.show_order(params[:type], params[:page], current_user.id)
    type = params["type"]
    if type.to_s == 'purchase'
      render :show_purchase_order
      return
    elsif type == "sell"
      render :show_sell_order
      return
    end
  end

  def approval
    @order.status = "Cancelled"
    respond_to do |format|
      if @order.save
        format.html { redirect_to request_manager_orders_path, notice: 'Requested Order was successfully approvaled.' }
        format.json { redirect_to request_manager_orders_path, status: :ok, location: @order }
      else
        format.html { redirect_to request_manager_orders_path }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_reject_status
    @order
  end

  def reject
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to request_manager_orders_path, notice: 'Status of Requested Order was successfully modofied.' }
        format.json { redirect_to request_manager_orders_path, status: :ok, location: @order }
      else
        format.html { redirect_to request_manager_orders_path }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def request_manager
    if current_user.has_role? :admin
      @requested_orders = Order.show_order('revoke', params[:page], current_user.id)
    else
      render :has_no_perimission
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  # delete one order
  def destroy
    @order.destroy
    respond_to do |format|
      @orders = Order.show_order("purchase", params[:page], current_user.id)
      format.html { render :show_purchase_order, notice: 'Refund request was successfully created.' }
      format.json { render :show_purchase_order, status: :ok, location: @order }
    end
  end

  def refund
    @order.status = "Pending"
    respond_to do |format|
      if @order.save
        @orders = Order.show_order("purchase", params[:page], current_user.id)
        format.html { render :show_purchase_order, notice: 'Refund request was successfully created.' }
        format.json { render :show_purchase_order, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  end

  def confirm
    @order.status = "Received"
    respond_to do |format|
      if @order.save
        @orders = Order.show_order("purchase", params[:page], current_user.id)
        format.html { render :show_purchase_order, notice: 'Refund request was successfully created.' }
        format.json { render :show_purchase_order, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def ship
    @order.status = "Shipped"
    respond_to do |format|
      if @order.save
        @orders = Order.show_order("sell", params[:page], current_user.id)
        format.html { render :show_sell_order, notice: 'Refund request was successfully created.' }
        format.json { render :show_sell_order, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:buyer_id, :seller_id, :status, :total_price, :postcode, :address, :phone, :product_id, :amount, :current_user_id)
    end
end

src/app/helpers/orders_helper.rb
module OrdersHelper
end

src/app/views/orders/check_out.html.erb
<h1> This is CheckOut </h1>

Card number: <input type="text" name="lname"><br>
Expired Date: <input type="text" name="lname"><br>
CSV: <input type="text" name="lname"><br>
First name: <input type="text" name="lname"><br>
Last name: <input type="text" name="lname"><br>

<%= button_to "Pay", { action: "pay"}, method: :get, data: { confirm: "Are you sure?" } %>

src/app/views/orders/create_cart_orders.html.erb
<h1> this is create cart orders</h1>
<p id="notice"><%= notice %></p>
Card number: <input type="text" name="lname"><br>
Expired Date: <input type="text" name="lname"><br>
CSV: <input type="text" name="lname"><br>
First name: <input type="text" name="lname"><br>
Last name: <input type="text" name="lname"><br>

<%= button_to "Pay", { action: "pay_for_orders"}, method: :get, data: { confirm: "Are you sure?" } %>

src/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

src/app/views/orders/has_no_perimission.html.erb
<h1>You do not have permission to do this action</h1>
<h>Please contact administrator if you supposed to have this right</h>

src/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Buyer</th>
      <th>Seller</th>
      <th>Status</th>
      <th>Total price</th>
      <th>Postcode</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.buyer_id %></td>
        <td><%= order.seller_id %></td>
        <td><%= order.status %></td>
        <td><%= order.total_price %></td>
        <td><%= order.postcode %></td>
        <td><%= order.address %></td>
        <td><%= order.phone %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

src/app/views/orders/new.html.erb
<h1> This is new in order </h1>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_id, value: @product_params[:product_id] %><br>
  <%= f.hidden_field :amount, value: @product_params[:amount] %><br>

  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.number_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', :back %>

src/app/views/orders/new_cart_orders.html.erb
<h2>Please Provide Receiver Information</h2>
<tbody>
    <%= form_tag('/orders/create_cart_orders') do %>
        <td><%= label_tag 'postcode' %></td>
        <td><%= number_field_tag 'postcode' %></td> </br>
        <td><%= label_tag 'name' %></td>
        <td><%= text_field_tag 'name' %></td> </br>
        <td><%= label_tag 'phone' %></td>
        <td><%= text_field_tag 'phone' %></td> </br>
        <td><%= label_tag 'address' %></td>
        <td><%= text_field_tag 'address' %></td> </br>
      <div><%= submit_tag 'Submit Order' %></div>
    <% end %>
  </tbody>


<%= link_to 'Back', :back %>

src/app/views/orders/pay_for_orders.html.erb
<h1> Your payment is successful, Thank you!<h1>

src/app/views/orders/payment.html.erb
<h1> payment complete </h1>

src/app/views/orders/purchase.html.erb
<h1>This is Purchase</h1>

src/app/views/orders/request_manager.html.erb
<h2> Orders requested for cancellation</h2>
<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
  <tr style = "text-align:center;">
    <th style = "text-align:center;">Id</th>
    <th style = "text-align:center;">Status</th>
    <th style = "text-align:center;">Total price</th>
    <th style = "text-align:center;">created_at</th>
    <th style = "text-align:center;">Detail</th>
    <th style = "text-align:center;">Approval</th>
    <th style = "text-align:center;">Reject</th>
  </tr>
  </thead>
  <tbody>
  <% @requested_orders.each do |order| %>
      <tr style = "text-align:center;">
        <td><%= link_to order.id, order%></td>
        <td><%= order.status %></td>
        <td><%= order.total_price %></td>
        <td><%= order.created_at.to_formatted_s(:long)  %></td>
        <td>
          <%= button_to "Detail", order_path(order), method: :get, class: "btn btn-primary" %>
        </td>
        <td>
          <%= button_to "Approval", approval_order_path(order), method: :get, class: "btn btn-primary" %>
        </td>
        <td>
       	  <%= button_to "Reject", update_reject_status_order_path(order), method: :get, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
     	</td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate(@requested_orders, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | " ) %>

src/app/views/orders/show_purchase_order.html.erb
<h2>My Purchase Orders</h2>
<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
  <tr style = "text-align:center;">
    <th style = "text-align:center;">Id</th>
    <th style = "text-align:center;">Status</th>
    <th style = "text-align:center;">Total price</th>
    <th style = "text-align:center;">created_at</th>
    <th style = "text-align:center;">Detail</th>
    <th style = "text-align:center;">Pay</th>
    <th style = "text-align:center;">Delete</th>
    <th style = "text-align:center;">Refund</th>
    <th style = "text-align:center;">ConfirmReceived</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr style = "text-align:center;">
        <td><%= link_to order.id, order%></td>
        <td><%= order.status %></td>
        <td><%= order.total_price %></td>
        <td><%= order.created_at.to_formatted_s(:long)  %></td>
        <td>
          <%= button_to "Detail", order_path(order), method: :get, class: "btn btn-primary" %>
        </td>

        <td>
          <% if order.status == 'unpaid' %>
          <%= button_to "Pay", pay_order_path(order), method: :get, class: "btn btn-primary" %>
          <% end %>
        </td>

        <td>
          <% if order.status == 'unpaid' || order.status == 'Received'%>
          <%= button_to "Delete", order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
          <% end %>
        </td>

      <td>
        <% if order.status != 'unpaid' && order.status != 'Cancelled' && order.status != 'Pending'%>
        <%= button_to "Refund", refund_order_path(order), method: :get, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
        <% end %>
      </td>
      <td>
        <% if order.status == 'Shipped' %>
        <%= button_to "ConfirmReceived", confirm_order_path(order), method: :get, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
        <% end %>
      </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%=will_paginate(@orders, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | " ) %>

src/app/views/orders/show_sell_order.html.erb
<h2>My Selling Orders</h2>
<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
  <tr style = "text-align:center;">
    <th style = "text-align:center;">Id</th>
    <th style = "text-align:center;">Status</th>
    <th style = "text-align:center;">Total price</th>
    <th style = "text-align:center;">created_at</th>
    <th style = "text-align:center;">Detail</th>
    <th style = "text-align:center;">Delete</th>
    <th style = "text-align:center;">Shipped</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr style = "text-align:center;">
        <td><%= link_to order.id, order%></td>
        <td><%= order.status %></td>
        <td><%= order.total_price %></td>
        <td><%= order.created_at.to_formatted_s(:long)  %></td>
        <td>
          <%= button_to "Detail", order_path(order), method: :get, class: "btn btn-primary" %>
        </td>

        <td>
          <% if order.status == 'unpaid' || order.status == 'Received'%>
        <%= button_to "Delete", order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
        <% end %>
      </td>

      <td>
        <% if order.status == 'Paid'%>
          <%= button_to "Shipped", ship_order_path(order), method: :get, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
        <% end %>
      </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%=will_paginate(@orders, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | " ) %>

src/app/views/orders/update_reject_status.html.erb
<h1> Choose a status </h1>
<%= form_for @order, url: reject_order_path(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :status %><br>
	<%= f.select(:status, ['Paid', 'Received', 'Shipped'], :class => 'my_style_class')%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', :back %>