src/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do 
      get :choose_new_type
      get :new_books
      get :new_cloth
      get :new_snacks
      get :category_products
      post :create_books
      post :create_snacks
      post :create_cloth
    end

    member do
      get :buy
      get :put_in_cart
    end
  end

  resources :cart_products do
    collection do
      get :show_cart
      get :update_quantity
    end
    member do
      get :destory
    end
  end

  resources :orders do
    collection do
      get :show_order
      post :new_cart_orders
      post :create_cart_orders
      get :pay_for_orders
      get :request_manager
    end

    member do
      get :purchase
      get :check_out
      get :pay
      delete :destroy
      get :approval
      get :update_reject_status
      patch :reject
      get :refund
      get :confirm
      get :ship
    end
  end

  devise_for :users

  root to: 'homepage#home'
  match '/help',    to: 'homepage#help',    via: 'get'
  match '/about',   to: 'homepage#about',   via: 'get'
  match '/contact', to: 'homepage#contact', via: 'get'
end

src/app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
	belongs_to :user

	# return products in the cart of the current user
	def self.show_cart(page, current_user_id)
			@cart_products = order("created_at DESC").where(user_id: current_user_id)
			@show_cart_list = []
				@cart_products.each do |cart_product|
					show_cart_item = {}
					product = Product.find cart_product.product_id
					show_cart_item[:id] = cart_product.id
					show_cart_item[:title] = product.title
					show_cart_item[:price] = product.price
					show_cart_item[:total] = product.price * cart_product.quantity
					show_cart_item[:quantity] = cart_product.quantity
					show_cart_item[:stock] = product.quantity
					show_cart_item[:created_at] = cart_product.created_at
					@show_cart_list << show_cart_item
				end
			@show_cart_list.paginate(page: page, per_page: 5)
	end

=begin
	 if the same product exists in the cart, return the CartProduct
	 else return nil
=end
	def self.ifSameProductExist (productId, current_user_id)
		@cart_products = CartProduct.where(user_id: current_user_id)
		@cart_products.each do |cart_product|
			if cart_product.product_id.to_s == productId
				return cart_product
			end
		end
		return nil
	end

	def self.update_quantity(cartProductId, quantity)
			cartProduct = CartProduct.find cartProductId
			product = Product.find cartProduct.product_id
			if quantity <= product.quantity
				cartProduct.update(quantity: quantity)
				return quantity
			else
				return product.quantity
			end
	end
end

src/app/models/user.rb
require 'role_model'
require 'rubygems'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include RoleModel
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cart_products
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :roles, :roles_mask

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :participant

  private
  ## Strong Parameters 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :roles, :roles_mask)
  end
end

src/app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :set_cart_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cart_products
  # GET /cart_products.json
  def index
    @cart_products = CartProduct.all
  end

  # GET /cart_products/1
  # GET /cart_products/1.json
  def show
    @product = Product.find @cart_product.product_id
  end

  # show all products in the cart of the current user
  def show_cart
    @show_cart_list = CartProduct.show_cart(params[:page], current_user.id )
  end

  # put a new product in the cart
  def new
    request_amount = params["amount"].to_i
    @product = Product.find params["productId"]
    product_quantity = @product.quantity

    if(CartProduct.ifSameProductExist(params["productId"], current_user.id))
      existedCartProduct = CartProduct.ifSameProductExist(params["productId"],current_user.id)
      if existedCartProduct.quantity+request_amount > product_quantity
        flash[:notice] = 'Sorry, the quantity of the product insufficient.'
        redirect_to @product
      end
      newquantity = existedCartProduct.quantity + request_amount
      existedCartProduct.update_attributes!(quantity: newquantity)
      # existedCartProduct.quantity += params["amount"].to_i
      # existedCartProduct.save!
      flash[:notice] = 'Cart product was successfully created.'
      redirect_to  existedCartProduct
    else
      if request_amount > product_quantity
        flash[:notice] = 'Sorry, the quantity of the product insufficient.'
        redirect_to @product
      end
      @product_params = {quantity: params["amount"], product_id: params["productId"]}
      @cart_product = CartProduct.new @product_params
      current_user.cart_products << @cart_product
      @cart_product.save!
      flash[:notice] = 'Cart product was successfully created.'
      redirect_to  @cart_product
    end
  end

  # GET /cart_products/1/edit
  def edit
  end

  # POST /cart_products
  # POST /cart_products.json
  def create
    @cart_product = CartProduct.new(cart_product_params)

    respond_to do |format|
      if @cart_product.save
        format.html { redirect_to @cart_product, notice: 'Cart product was successfully created.' }
        format.json { render :show, status: :created, location: @cart_product }
      else
        format.html { render :new }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_products/1
  # PATCH/PUT /cart_products/1.json
  def update
    request_amount = params["amount"].to_i
    @product = Product.find params["productId"]
    product_quantity = @product.quantity
    respond_to do |format|
      if @cart_product.update(cart_product_params)
        format.html { redirect_to @cart_product, notice: 'Cart product was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_product }
      else
        format.html { render :edit }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_quantity
    respond_to do |format|
        format.html
        format.json {render json: CartProduct.update_quantity(params["cartProductId"].to_i, params["quantity"].to_i)}
    end
  end



  # DELETE /cart_products/1
  # DELETE /cart_products/1.json
  # delete one product from the cart
  def destroy

    @cart_product = CartProduct.find(params[:id])

    @cart_product.destroy
    flash[:notice] = 'The product has been deleted from the cart.'
    redirect_to :controller => 'cart_products', :action => 'show_cart'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_product
      @cart_product = CartProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_product_params
      params.require(:cart_product).permit(:cart_id, :product_id, :quantity)
    end
end

src/app/helpers/cart_products_helper.rb
module CartProductsHelper
end

src/app/views/cart_products/_form.html.erb
<%= form_for(@cart_product) do |f| %>
  <% if @cart_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_product.errors.count, "error") %> prohibited this cart_product from being saved:</h2>

      <ul>
      <% @cart_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/cart_products/edit.html.erb
<h1>Editing Cart Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_product %> |
<%= link_to 'Back', cart_products_path %>

src/app/views/cart_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Products</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_products.each do |cart_product| %>
      <tr>
        <td><%= cart_product.user_id %></td>
        <td><%= cart_product.product_id %></td>
        <td><%= cart_product.quantity %></td>
        <td><%= link_to 'Show', cart_product %></td>
        <td><%= link_to 'Edit', edit_cart_product_path(cart_product) %></td>
        <td><%= link_to 'Destroy', cart_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart product', new_cart_product_path %>

src/app/views/cart_products/new.html.erb
<h1>New Cart Product</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_products_path %>

src/app/views/cart_products/show.html.erb
<dl class="dl-horizontal">
  <dt> Name:</dt>
  <dd><%= @product.name %></dd>
  <dt> Unit price:</dt>
  <dd><%= @product.price %></dd>
  <dt> Quantity:</dt>
  <dd><%= @cart_product.quantity %></dd>
  <dt> Total Price:</dt>
  <dd><%= @product.price * @cart_product.quantity %></dd>
</dl>
<div class="btn-toolbar" role="toolbar" >
  <div class="btn-group" role="group" aria-label="Checkout">
    <%= link_to 'Check out', '/orders/new?productId='+ @product.id.to_s + '&amount='+ @cart_product.quantity.to_s, class: "btn btn-info"%>
  </div>
  <div class="btn-group" role="group" aria-label="Back">
    <%= link_to 'Back', :back, class: "btn btn-info"%>
  </div>
</div>

src/app/views/cart_products/show_cart.html.erb
<h2>My Cart Products</h2>
<p id="notice"><%= notice %></p>

<%= form_tag('/orders/new_cart_orders') do %>
<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
  <tr style = "text-align:center;">
    <th style= "width:30px"></th>
    <th style = "text-align:center;">Title</th>
    <th style = "text-align:center;">unit price</th>
    <th style = "text-align:center;">Quantity</th>
    <th style = "text-align:center;">Total price</th>
    <th style = "text-align:center;">Delete</th>
  </tr>
  </thead>
  <tbody>

      <% @show_cart_list.each do |show_cart_item| %>
          <tr>
            <td><%= check_box_tag "cart_product_ids[]", show_cart_item[:id], :id => "cart_product_ids_#{show_cart_item[:id]}" %> </td>
            <td><%= show_cart_item[:title] %></td>
            <td><%= show_cart_item[:price] %></td>
            <td ><%= number_field( :purchase, :quantity, in: 1..show_cart_item[:stock], step: 1, value: show_cart_item[:quantity])%></td>
            <td><%= show_cart_item[:total] %></td>
            <td><%= link_to 'Delete', "/cart_products/#{show_cart_item[:id]}", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %></td>
          </tr>
      <% end %>

  </tbody>
</table>
      <div>
        <%= submit_tag 'Check Out' , class: "btn btn-primary" %>
      </div>
  <% end %>

<br>


<%=will_paginate(@show_cart_list, :prev_label=>'Previous', :next_label=>'Next', :separator=>" | ") %>