src/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do 
      get :choose_new_type
      get :new_books
      get :new_cloth
      get :new_snacks
      get :category_products
      post :create_books
      post :create_snacks
      post :create_cloth
    end

    member do
      get :buy
      get :put_in_cart
    end
  end

  resources :cart_products do
    collection do
      get :show_cart
      get :update_quantity
    end
    member do
      get :destory
    end
  end

  resources :orders do
    collection do
      get :show_order
      post :new_cart_orders
      post :create_cart_orders
      get :pay_for_orders
      get :request_manager
    end

    member do
      get :purchase
      get :check_out
      get :pay
      delete :destroy
      get :approval
      get :update_reject_status
      patch :reject
      get :refund
      get :confirm
      get :ship
    end
  end

  devise_for :users

  root to: 'homepage#home'
  match '/help',    to: 'homepage#help',    via: 'get'
  match '/about',   to: 'homepage#about',   via: 'get'
  match '/contact', to: 'homepage#contact', via: 'get'
end

src/app/views/layouts/_footer.html.erb
<footer class="footer" style="margin-top: 200px">
  <small>
    The <a href="#">ebuy</a>
     is your shopping paradise</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

src/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ebuy", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>

          <% if current_user.has_role? :admin %>
          <li><%= link_to "Manage Request", "/orders/request_manager" %></li>
          <% end %>

          <li><%= link_to "Sell", "/products/choose_new_type" %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Order <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "check purchase", "/orders/show_order?type=purchase" %></li>
              <li><%= link_to "check sells", '/orders/show_order?type=sell' %></li>
            </ul>
          </li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cart <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Cart", '/cart_products/show_cart' %></li>
            </ul>
          </li>
           <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Change Password", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class = "navigation">
<div class = "search">
  <%= form_tag products_path, :method => :get do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name=>nil%>
  <% end %>
</div>

<div class = "product-navigation">
  <ul class="nav nav-tabs">
    <li class = "active"><%= link_to "Home", root_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        Cloth <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
    <li><a href="/products/category_products?type=Cloth&category=Top">Tops</a></li>
    <li><a href="/products/category_products?type=Cloth&category=Bottom">Bottoms</a></li>
    <li><a href="/products/category_products?type=Cloth&category=Outwear">OutWears</a></li>
      </ul>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        Book <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="/products/category_products?type=Book&category=Textbook">Textbooks</a></li>
        <li><a href="/products/category_products?type=Book&category=ChildrenBook">Children's Books</a></li>
        <li><a href="/products/category_products?type=Book&category=Novel">Novel</a></li>
      </ul>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        Snack <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="/products/category_products?type=Snack&category=ChipsCrips">Chips & Crips</a></li>
        <li><a href="/products/category_products?type=Snack&category=Cookies">Cookies</a></li>
        <li><a href="/products/category_products?type=Snack&category=Jerky">Jerky</a></li>
        <li><a href="/products/category_products?type=Snack&category=NutsSeeds">Nuts & Seeds</a></li>
      </ul>
    </li>
  </ul>
</div>
</div>

src/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>